---
title: Kona Beer
output:
  html_document:
    keep_md: yes
    toc: yes
---



<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of two directories.-->
```{r, echo=F, message=F} 
# cat("Working directory: ", getwd())
  library(knitr)
  opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# cat("Working directory: ", getwd())
opts_chunk$set(
  results    = 'show', 
  comment    = NA, 
  tidy       = FALSE,
  fig.width  = 4, 
  fig.height = 4, 
  fig.path   = 'figure-png/'
)
# dpi = 400,
# out.width = "650px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.

echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./analysis/kona-beer.R") #This allows knitr to call chunks tagged in the underlying *.R file.
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load_sources, echo=echoChunks, message=FALSE}
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load_packages, echo=echoChunks, message=FALSE}
```

<!-- Load any global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare_globals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=echoChunks, message=FALSE}
#Put presentation-specific code in here.  It doesn't call a chunk in the codebehind file.
```

<!-- Load the datasets.   -->
```{r load_data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak_data, echo=echoChunks, results='show', message=FALSE}
```
See [html version](./kona-beer.html)

## Data
The data for each beer were collected from the official Kona Brewery [website](http://konabrewingco.com/). 

```{r echo=FALSE}
ds
```



##1
```{r scatter_1, echo=echoChunks, results='show', message=FALSE, warning=FALSE, fig.width=10, fig.height=8}
g <- ggplot2::ggplot(ds, aes(x=bitterness, y=alcohol, fill=type)) + 
  geom_point(shape=21, size=6) +
  geom_text(aes(label = beer, hjust = -0.15)) +
  main_theme 
g 

```

##2
Keep in mind that alcohol (ABV - alcohol by volume) and gravity (original gravity) are higly correlated

```{r scatter_2, echo=echoChunks, results='show', message=FALSE, warning=FALSE, fig.width=10, fig.height=8}
d <- ds[!ds$beer == "Kua Bay" ,]
g <- ggplot2::ggplot(d, aes(x=gravity, y=alcohol, fill=type)) + 
  geom_point(shape=21, size=6) +
  geom_text(aes(label = beer, hjust = -0.15)) +
  main_theme 
g 

cor(d$alcohol, d$gravity)

```


# Session Information
For the sake of documentation and reproducibility, the current report was rendered on a system using the following software.

```{r session_info, echo=FALSE}
cat("Report rendered by", Sys.info()["user"], "at", strftime(Sys.time(), "%Y-%m-%d, %H:%M %z"))
sessionInfo()
```
